name: build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      platform:
        default: 'ubuntu-latest'
        required: true
        type: string
      target:
        default: 'x86_64-unknown-linux-gnu'
        required: true
        type: string


jobs:
  cross-build:
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build release
        run: cargo build --release --target ${{ inputs.target }}
      - name: Upload release
        uses: softprops/action-gh-release@v2.4.2
        with:
          tag_name: ${{ inputs.version }}
          files: target/${{ inputs.target }}/release/${{ inputs.name }}
          draft: false
          prerelease: false
          overwrite_files: true
