name: ci

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  CARGO: "Cargo.toml"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/ci.yml"
      - "Cargo.toml"

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      path: ${{ env.CARGO }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"
  parse:
    needs:
      - pre
    uses: ./.github/workflows/parse.yml
    with:
      path: ${{ needs.pre.outputs.path }}
  release:
    needs:
      - parse
    uses: ./.github/workflows/release.yml
    with:
      name: ${{ needs.parse.outputs.name }}
      version: ${{ needs.parse.outputs.version }}